@tenant = TENANT
@clientID = CLIENTID
@clientSecret= CLIENTSECRET
POST /{{tenant}}/oauth2/v2.0/token
Host: login.microsoftonline.com:443
Content-Type: application/x-www-form-urlencoded

client_id={{clientID}}
&scope=https://graph.microsoft.com/.default
&client_secret={{clientSecret}}
&grant_type=client_credentials